client:
    resource: "@ClientBundle/Controller/"
    type:     annotation
    prefix:   /

resto:
    resource: "@RestoBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation
