client:
    resource: "@RestoBundle/Resources/config/routing.yml"
    prefix:   /
resto:
    resource: "@ClientBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation
